#!/bin/sh /etc/rc.common

START=21

((sleep 10 ; /lib/gluon/erx-upgrade/download-config.sh ||: ; sleep 10 ; /lib/gluon/erx-upgrade/download-config.sh ||: ; sleep 10 ; /lib/gluon/erx-upgrade/download-config.sh ||:) &)
